import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Work_Sans } from "next/font/google";

const work = Work_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-work",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${work.className} mt-4 min-h-screen bg-[#FFFFFF] dark:bg-[#181A2A] transition-colors antialiased`}
      >
        <div className="sm:mx-28 mx-2">
          <Navbar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
